#!/usr/bin/env bash
set -euo pipefail

# Step 2: Create SonarQube project and generate token via API
# Reference: https://next.sonarqube.com/sonarqube/web_api/api/projects
# Reference: https://next.sonarqube.com/sonarqube/web_api/api/user_tokens

SONAR_URL="${SONAR_URL:-http://localhost:9000}"
SONAR_ADMIN_USER="${SONAR_ADMIN_USER:-admin}"
SONAR_ADMIN_PASS="${SONAR_ADMIN_PASS:-admin}"
PROJECT_KEY="sonarqube-agent-test"
PROJECT_NAME="SonarQube AI Agent Test Project"
TOKEN_NAME="agent-token"

echo "=== Step 2: Setting up SonarQube project and token ==="

echo "[1/4] Checking SonarQube availability..."
STATUS=$(curl -sf "$SONAR_URL/api/system/status" | grep -o '"status":"[^"]*"' | cut -d'"' -f4)
if [[ "$STATUS" != "UP" ]]; then
    echo "[ERROR] SonarQube is not running. Run 01-start-sonarqube.sh first."
    exit 1
fi
echo "  SonarQube status: $STATUS"

echo "[2/4] Creating project: $PROJECT_KEY"
HTTP_CODE=$(curl -sf -o /dev/null -w "%{http_code}" \
    -u "$SONAR_ADMIN_USER:$SONAR_ADMIN_PASS" \
    -X POST "$SONAR_URL/api/projects/create" \
    -d "project=$PROJECT_KEY&name=$PROJECT_NAME" 2>/dev/null || echo "000")

if [[ "$HTTP_CODE" == "200" ]]; then
    echo "  Project created successfully."
elif [[ "$HTTP_CODE" == "400" ]]; then
    echo "  Project already exists (OK)."
else
    echo "  [WARN] Unexpected response: HTTP $HTTP_CODE"
fi

echo "[3/4] Generating user token: $TOKEN_NAME"
# Delete existing token if present
curl -sf -u "$SONAR_ADMIN_USER:$SONAR_ADMIN_PASS" \
    -X POST "$SONAR_URL/api/user_tokens/revoke" \
    -d "name=$TOKEN_NAME" > /dev/null 2>&1 || true

TOKEN_RESPONSE=$(curl -sf \
    -u "$SONAR_ADMIN_USER:$SONAR_ADMIN_PASS" \
    -X POST "$SONAR_URL/api/user_tokens/generate" \
    -d "name=$TOKEN_NAME")

TOKEN=$(echo "$TOKEN_RESPONSE" | grep -o '"token":"[^"]*"' | cut -d'"' -f4)

if [[ -z "$TOKEN" ]]; then
    echo "[ERROR] Failed to generate token."
    echo "  Response: $TOKEN_RESPONSE"
    exit 1
fi

echo "  Token generated successfully."

echo "[4/4] Writing .env file..."
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$(dirname "$SCRIPT_DIR")/.env"

cat > "$ENV_FILE" << EOF
# Auto-generated by 02-setup-project.sh
# DO NOT COMMIT THIS FILE
SONAR_URL=$SONAR_URL
SONAR_TOKEN=$TOKEN
SONAR_PROJECT_KEY=$PROJECT_KEY
EOF

echo ""
echo "=== Setup Complete ==="
echo "  Project:  $PROJECT_KEY"
echo "  Token:    ${TOKEN:0:8}...${TOKEN: -4} (saved to .env)"
echo "  .env:     $ENV_FILE"
echo ""
echo "  Next: Run 03-run-scan.sh to analyze the sample project."
